### ISSUE TITLE
Broken when NRQL statement has '%'

### ISSUE THREAD

**Issue by deeduda** [AnthonyBloomer/nrql-simple#1]
I have to hack it to get it to work with '%' in query_stmt else it gave me: status_code :400. The url is not encoded properly when '%' present.

Hack.....

INSIGHTS_URL = "https://insights-api.newrelic.com/v1/accounts/%s/query"

    def _make_request(self, query_stmt):
        payload = {'nrql':query_stmt}
        req = requests.get(self._url % (self.account_id),
                           headers={"X-Query-Key": self.api_key},params=payload)

**Comment by AnthonyBloomer** [comment]
Hi @deeduda, thank you for reporting this issue! I've used the workaround you provided. I will include this in the next release.
