### ISSUE TITLE
nrql does not report its version

### ISSUE THREAD

**Issue by atsalolikhin-spokeo** [AnthonyBloomer/nrql-simple#11]
Hi,

Not to barrage you, but I just opened another issue and I was going to tell you what version of nrql-cli I'm using but I can't:

```
[~/nrql-cli] [nrql-cli] $ nrql --version
usage: nrql_cli [-h] [--region {EU,US}] [--env ENV] [--verbose]
nrql_cli: error: unrecognized arguments: --version
[~/nrql-cli] [nrql-cli] $
```

Not a showstopper, I installed it with `pip` so I can get the version from there:

```
[~/nrql-cli] [nrql-cli] $ pip freeze | grep nrql-cli
nrql-cli==1.0.3
[~/nrql-cli] [nrql-cli] $
```

**Comment by AnthonyBloomer** [comment]
Thank you, @atsalolikhin-spokeo. I will get this included.
